[project]
name = "project-chimera-10x-3-days-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.26.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.46",
]

[project.optional-dependencies]
dev = [
    "bandit>=1.7.8",
    "ruff>=0.8.0",
]
